#!/usr/bin/env python
# -*- coding: utf-8 -*-

from typing import Dict, Any

from swarm.environment.prompt.prompt_set import PromptSet
from swarm.environment.prompt.prompt_set_registry import PromptSetRegistry
from swarm.environment.prompt.common import get_combine_materials


@PromptSetRegistry.register('medqa')
class MedQAPromptSet(PromptSet):

    @staticmethod
    def get_role():
        return "knowledgable medical expert in multiple-choice question answering"

    @staticmethod
    def get_constraint():
        return """
            I will ask you a medical multiple-choice question.
            I will also give you up to 5 answers enumerated as A, B, C, D and E.
            Only one answer out of the offered options is correct.
            You must choose the correct answer to the question.
            Your response must be one of the letters: A, B, C, D or E,
            corresponding to the correct answer.
            Provide your reasoning by showing your work after your answer.
            At the head of your response, output your final answer in the format: 'Answer: [answer]'.
        """

    @staticmethod
    def get_format():
        return "one of the letters: A, B, C, D or E"

    @staticmethod
    def get_answer_prompt(question):
        return f"""{question}"""

    @staticmethod
    def get_answer_prompt_refine_last_answers(question, last_answer_list):

        prompt = f"You have been provided with a set of responses from various open-source models to the latest user query, which is {question}.\
            Your task is to synthesize these responses into a single, high-quality response. \
            It is crucial to critically evaluate the information provided in these responses, recognizing that some of it may be biased or incorrect. \
            Your response should not simply replicate the given answers but should offer a refined, accurate, and comprehensive reply to the instruction. \
            Ensure your response is well-structured, coherent, and adheres to the highest standards of accuracy and reliability.\n"
        prompt += f"Once again, the query is: {question}\n"

        for i, reference in enumerate(last_answer_list):
            prompt += f"\n{i+1}. {reference}"

        return prompt

    @staticmethod
    def get_query_prompt(question):
        raise NotImplementedError

    @staticmethod
    def get_file_analysis_prompt(query, file):
        raise NotImplementedError

    @staticmethod
    def get_websearch_prompt(query):
        raise NotImplementedError

    @staticmethod
    def get_adversarial_answer_prompt(question):
        return f"""Answer a lie to the following question: {question}. """

    @staticmethod
    def get_distill_websearch_prompt(query, results):
        raise NotImplementedError

    @staticmethod
    def get_reflect_prompt(question, answer_list):

        prompt = f"""According to the previous agents' answers and reasoning in the **MedQA** task:
Question: {question}

As the **fusion reviewer**, your goal is to synthesise a high-quality final answer by
integrating the best reasoning among all responses while keeping the result concise
and directly usable by the next agent.  Follow these guidelines:

Only retain the final selected answer (single letter, e.g., A, B, C, D, or E).

Keep reasoning sentences that directly explain why this choice is better than others. Ensure that the reasoning process is both correct and logically rigorous.

Remove any redundant details, repeated phrases, or overly long explanations.

Focus only on the reasoning relevant for the next agent's task; drop unrelated side discussions.

Most importantly, the output must be clear and directly usable by the next agent. Do not only check the errors in the answer and reasoning, but also the logic of reasoning.

Now, you should check the above rules one by one and review the answer + reasoning in detail,
propose one simplified summary that condenses the answer and key reasoning.

Return your summary strictly in the following format:
<OUTPUT> 
Answer: C
Reasoning: C covers both A and B; neither A nor B alone is sufficient.
</OUTPUT> 
"""

        for i, ans in enumerate(answer_list, start=1):
            prompt += f"{i}. {ans}\n"
        return prompt


    @staticmethod
    def get_select_best(question, solutions) -> str:
        return MedQAPromptSet.get_answer_prompt_refine_last_answers(question, solutions)

    @staticmethod
    def get_combine_materials(materials: Dict[str, Any]) -> str:
        return get_combine_materials(materials)

    @staticmethod
    def get_summary(answer: str, task: str) -> str:
        prompt = f"""
    You are a **summary agent** in a multi-agent MMLU reasoning system.

    Task (question stem):
    {task}

    The following answer was generated by a previous agent, but it may contain
    redundant explanations, repeated phrases, hallucinations, or flawed logic.
    Your job is to **clean and summarise** this answer using the rules below:

    1. **Keep only the final chosen option letter** (A / B / C / D / E).  
    2. Retain at most **1–2 concise sentences of reasoning** that directly justify why this letter is
    the best choice over the other options.  
    3. **Remove** any repetition, filler words, unrelated side notes, or overly long derivations.  
    4. If the reasoning is clearly wrong or hallucinated, **either fix it succinctly** or omit it
    and output only the letter.  
    5. **Do NOT invent new facts** not present in the original answer or the question.  
    6. If no valid reasoning remains, just output the letter (no reasoning line).  
    7. Output must follow **exactly** the format below — nothing more, nothing less.

    Return your cleaned summary strictly in the following format:

    <OUTPUT>
    Answer: <single uppercase letter>
    Reasoning: <short explanation of the core reasoning steps used to get this result, if no reasoning is present in the previous answer, ignore this.>
    </OUTPUT>

    Original Answer:
    \"\"\"
    {answer}
    \"\"\"
    """
        return prompt
    
    @staticmethod
    def get_verifier(answer,task):
        prompt = f"""
We are solving a MedQA task.

Question:
{task}

Below is a candidate answer from an agent.

As the **VERIFIER**, evaluate this answer on:
- **Choice correctness** — Does the letter match the true correct option?
- **Reasoning quality** — Is the justification logically sound, concise, and relevant?
- **Clarity** — Is the response free of unnecessary or confusing content?

Then, provide:
1. A **score** between 0 and 10 indicating the quality of the answer.
2. A **brief reason** for the score.

Format your response strictly as follows:
Score: <number from 0 to 10>  
Reason: <short explanation of why this score was given>

Please remember: if you believe the answer is incorrect, the score you assign should not exceed 3.

Candidate Answer:
{answer}
"""
        return prompt
    
    @staticmethod
    def get_model_initialize(model_combo):
        prompt = f"""
You are a researcher specializing in multi-agent systems (MAS).  
Your current task is **model initialization**: under a fixed computational **budget** you must choose an initial set of language-model agents (each model = one node) for a MAS that will later be optimized into a DAG. An edge means the previous agent’s output is the next agent’s input.

================  TASK  =================
1. Examine the **candidate model combinations** listed at the end of this message.  
2. Using the insights and data below, pick **two** combination that will give the best expected performance on the **MedQA** dataset.  
3. Return **only** two JSON dictionaries with four integer keys:  
   - `"0"` = number of 3 B models  
   - `"1"` = number of 8 B models  
   - `"2"` = number of 70 B models  
   - `"3"` = number of 405 B models  

No extra text, explanations, or formatting—just the dictionary.

===============  INSIGHTS  ===============
(1) Well-designed MASes usually improve as the number of nodes increases, **but**  
    • very long contexts fed to a weak model can hurt accuracy, and  
    • overly deep DAGs may let later agents overwrite correct answers.
    • both depth and width have an optimal point—beyond that, adding more layers or parallel branches starts to decrease overall performance.
    • Too many weak models may decrease the performance instead of increase.
(2) Stronger models (better performance) tolerate longer context and are less likely to corrupt correct answers.  
(3) You must trade off “more nodes help” vs. “too many weak models hurt”. Choose the mix that best balances these forces.
(4) You may refer to the 'Data' section showing the performance of different model combinations under the same budget on this dataset to help you decide which two model selection are the best candidates among the current model selection options.

===============  DATA  ===================
● **Single-model accuracy on MedQA (higher is better)**  
1 B → 28   3 B → 29   8 B → 48   70 B → 84
● Random-graph pre-experiments (equal budget):
9X3 B → 30   2X8B + 3X3B → 45  3X8B → 48  1X70B → 64  

===============  CANDIDATES  =============
Choose only **one** from this list (each already fits the budget):

{model_combo}

=========================================

Respond with the dictionary **only**. Example format (do NOT copy):  
```json
{{"0":0,"1":4,"2":0,"3":0}}
```json
{{"0":0,"1":1,"2":1,"3":0}}
"""
        return prompt

    @staticmethod
    def get_llm_forward(prev_graph,acc,edge_probs,model_selection):

        prompt = f"""
You are a professional **Multi-Agent-System (MAS) optimizer**.  
Your task is an iterative self-RL refinement of a MAS that solves the **MedQA** dataset.

────────────────────────────────────
TASK CONTEXT
────────────────────────────────────
• A MAS is represented as a **directed acyclic graph (DAG)**.  
  - Each **node** = one language-model agent.  
  - Each **directed edge** = “the source agent's output is appended to the destination agent's context”.  
• For the current budget we have a fixed **model-selection requirement**:  
  {model_selection}
• You will see the **last-round graph**, its **batch accuracy**, and the **full table of edge-selection probabilities**.  
• Your job: **propose the next-round graph** (same format) **and the updated probability table** (same order & format), applying * RL-style* probability nudges.
• The graph you receive in this iteration has been expanded outward from the FinalDecision node, gradually increasing in both depth and breadth. The edge-probabilities starts with all edge probabilities set to zero, and through multiple sampling rounds, probabilities are raised only for edges that prove useful.

────────────────────────────────────
HISTORICAL SNAPSHOT
────────────────────────────────────
Last-round accuracy ( MedQA-dev batch ) : **{acc:.3%}**  
Last-round graph:  
{prev_graph}
Last-round edge-probabilities:
{edge_probs}

────────────────────────────────────
OPTIMIZATION RULES
────────────────────────────────────
R-1  Model counts must exactly match model_selection after you assign models to all nodes.
R-2  A node's role is either "IO" (generates new answer) or "REV" (reviews & picks best).
R-3  Return values must keep the identical schema / key order as the inputs — only the values may change.
R-4  Increase an edge probability **only if it was sampled in the last-round graph AND proved useful**.  
Always start expansion from FinalDecision's incoming edges, then its parents' incoming edges, and so on.
↑ increase edges used by high-accuracy graphs, ↓ decrease edges from poor graphs.
R-5  Keep the graph acyclic; avoid too much in-degree to prevent context explosion; avoid very deep chains to prevent “answer corruption”.
R-6 If a node appears with model = FinalDecision (this is the single output node of the MAS), do not modify its model or role.
Your optimization may only update the set/probabilities of its incoming edges — that is, adjust which predecessors feed it and with what likelihood—but the node itself must stay unchanged.

────────────────────────────────────
DATA and Insight
────────────────────────────────────
• Model accuracy on MedQA (single-agent):
1 B → 28   3 B → 29   8 B → 48   70 B → 84

• Larger models tolerate longer context and are harder to corrupt.
• Larger models outperform smaller models when assigned the nodes with more predecessors.
• For nodes with multiple incoming edges, assigning diverse models to their predecessors often yields better performance than using a single repeated model.
• The optimal depth is conditioned by current width, and vice-versa: wider graphs shift the depth sweet-spot downward, while deeper graphs reduce the optimal width.
• You should expand the architecture outward from the FinalDecision node, gradually adding depth and breadth.
• Different tasks favor different graph topologies depending on the model mix. Certain model configurations benefit more from greater depth, while others perform best with greater width. With the current model selection, optimize toward the topology style that this task prefers.
• For this round, increase probabilities only for nodes that boost MAS accuracy, and lower those that harm it.

────────────────────────────────────
WHAT TO RETURN
────────────────────────────────────
Return ONLY two blocks, nothing else.
	1.	graph - the next-round DAG, same schema as last-round graph.
	2.	edge_probs - the updated probability table, same schema and order as last-round edge-probabilities.
IMPORTANT: The "Graph:" block must list exactly the same nodes as in the last-round graph. Do NOT create any new node lines. Do NOT change any node ID token.
    
Example output format (do NOT add comments):
Graph:
"Node 3CoH | model=llama3.2-3b-longcontext:latest | role=IO | preds=['4Dhq'] | succs=[]\nNode 4Dhq | model=llama3.2-1b-longcontext:latest | role=IO | preds=[] | succs=['3CoH', 'cFSM']\nNode 5XF3 | model=llama3.2-1b-longcontext:latest | role=IO | preds=['cFSM'] | succs=[]\nNode 6S5Q | model=FinalDecision | role=IO | preds=['cFSM'] | succs=[]\nNode cFSM | model=llama3.2-3b-longcontext:latest | role=REV | preds=['4Dhq'] | succs=['5XF3', '6S5Q']"
Edge-probabilities:
['0: src=DirectAnswer(5XF3), dst=DirectAnswer(3CoH), prob=0.000\n', '1: src=DirectAnswer(5XF3), dst=DirectAnswer(4Dhq), prob=0.000\n', '2: src=DirectAnswer(5XF3), dst=DirectAnswer(cFSM), prob=0.000\n', '3: src=DirectAnswer(3CoH), dst=DirectAnswer(5XF3), prob=0.000\n', '4: src=DirectAnswer(3CoH), dst=DirectAnswer(4Dhq), prob=0.000\n', '5: src=DirectAnswer(3CoH), dst=DirectAnswer(cFSM), prob=0.000\n', '6: src=DirectAnswer(4Dhq), dst=DirectAnswer(5XF3), prob=0.000\n', '7: src=DirectAnswer(4Dhq), dst=DirectAnswer(3CoH), prob=0.100\n', '8: src=DirectAnswer(4Dhq), dst=DirectAnswer(cFSM), prob=0.150\n', '9: src=DirectAnswer(cFSM), dst=DirectAnswer(5XF3), prob=0.00\n', '10: src=DirectAnswer(cFSM), dst=DirectAnswer(3CoH), prob=0.000\n', '11: src=DirectAnswer(cFSM), dst=DirectAnswer(4Dhq), prob=0.000\n', '12: src=DirectAnswer(5XF3), dst=FinalDecision(6S5Q), prob=0.000\n', '13: src=DirectAnswer(3CoH), dst=FinalDecision(6S5Q), prob=0.000\n', '14: src=DirectAnswer(4Dhq), dst=FinalDecision(6S5Q), prob=0.000\n', '15: src=DirectAnswer(cFSM), dst=FinalDecision(6S5Q), prob=0.100\n']

Now think step-by-step with the rules and insights above and return the Graph and Edge-probabilities two blocks only.
Disallow the following symbol-sequence pattern: a single space, then several arbitrary tokens, followed by a placeholder or ellipsis.
"""
        return prompt
    
    @staticmethod
    def get_model_initialize_textgrad(model_combo):
        prompt = f"""
You are a researcher specializing in multi-agent systems (MAS).  
Your current task is **model initialization**: under a fixed computational **budget** you must choose an initial set of language-model agents (each model = one node) for a MAS that will later be optimized into a DAG. An edge means the previous agent’s output is the next agent’s input.

================  TASK  =================
1. Examine the **candidate model combinations** listed at the end of this message.  
2. Based on your knowledge of test-time scaling, pick **one** combination that will give the best expected performance on the **MedQA** dataset.  
3. Return **only** a JSON dictionary with four integer keys:  
   - `"0"` = number of 1 B models  
   - `"1"` = number of 3 B models  
   - `"2"` = number of 8 B models  
   - `"3"` = number of 70 B models  

No extra text, explanations, or formatting—just the dictionary.

===============  CANDIDATES  =============
Choose only **one** from this list (each already fits the budget):

{model_combo}

=========================================

Respond with the dictionary **only**. Example format (do NOT copy):  
```json
{{"0":7,"1":3,"2":0,"3":0}}
"""
        return prompt

    @staticmethod
    def get_llm_forward_textgrad(prev_graph,acc,edge_probs,model_selection):

        prompt = f"""
You are a professional **Multi-Agent-System (MAS) optimizer**.  
Your task is an iterative self-RL refinement of a MAS that solves the **MedQA** dataset.

────────────────────────────────────
TASK CONTEXT
────────────────────────────────────
• A MAS is represented as a **directed acyclic graph (DAG)**.  
  - Each **node** = one language-model agent.  
  - Each **directed edge** = “the source agent's output is appended to the destination agent's context”.  
• For the current budget we have a fixed **model-selection requirement**:  
  {model_selection}
• You will see the **last-round graph**, its **batch accuracy**, and the **full table of edge-selection probabilities**.  
• Your job: **propose the next-round graph** (same format) **and the updated probability table** (same order & format), applying * RL-style* probability nudges.

────────────────────────────────────
HISTORICAL SNAPSHOT
────────────────────────────────────
Last-round accuracy ( MedQA-dev batch ) : **{acc:.3%}**  
Last-round graph:  
{prev_graph}
Last-round edge-probabilities:
{edge_probs}

────────────────────────────────────
OPTIMIZATION RULES
────────────────────────────────────
R-1  Model counts must exactly match model_selection after you assign models to all nodes.
R-2  A node's role is either "IO" (generates new answer) or "REV" (reviews & picks best).
R-3  Return values must keep the identical schema / key order as the inputs — only the values may change.
R-4  Keep the graph acyclic.
R-5  If a node appears with model = FinalDecision (this is the single output node of the MAS), do not modify its model or role.
Your optimization may only update the set/probabilities of its incoming edges — that is, adjust which predecessors feed it and with what likelihood—but the node itself must stay unchanged.

────────────────────────────────────
WHAT TO RETURN
────────────────────────────────────
Return ONLY two blocks, nothing else.
	1.	graph - the next-round DAG, same schema as last-round graph.
	2.	edge_probs - the updated probability table, same schema and order as last-round edge-probabilities.
IMPORTANT: The "Graph:" block must list exactly the same nodes as in the last-round graph. Do NOT create any new node lines. Do NOT change any node ID token.
    
Example output format (do NOT add comments):
Graph:
"Node 3CoH | model=llama3.2-3b-longcontext:latest | role=IO | preds=['4Dhq'] | succs=[]\nNode 4Dhq | model=gemma3-1b-longcontext:latest | role=IO | preds=[] | succs=['3CoH', 'cFSM']\nNode 5XF3 | model=gemma1-7b-longcontext:latest | role=IO | preds=['cFSM'] | succs=[]\nNode 6S5Q | model=FinalDecision | role=IO | preds=['cFSM'] | succs=[]\nNode cFSM | model=llama3.2-3b-longcontext:latest | role=REV | preds=['4Dhq'] | succs=['5XF3', '6S5Q']"
Edge-probabilities:
['0: src=DirectAnswer(5XF3), dst=DirectAnswer(3CoH), prob=0.000\n', '1: src=DirectAnswer(5XF3), dst=DirectAnswer(4Dhq), prob=0.000\n', '2: src=DirectAnswer(5XF3), dst=DirectAnswer(cFSM), prob=0.000\n', '3: src=DirectAnswer(3CoH), dst=DirectAnswer(5XF3), prob=0.000\n', '4: src=DirectAnswer(3CoH), dst=DirectAnswer(4Dhq), prob=0.000\n', '5: src=DirectAnswer(3CoH), dst=DirectAnswer(cFSM), prob=0.000\n', '6: src=DirectAnswer(4Dhq), dst=DirectAnswer(5XF3), prob=0.000\n', '7: src=DirectAnswer(4Dhq), dst=DirectAnswer(3CoH), prob=0.100\n', '8: src=DirectAnswer(4Dhq), dst=DirectAnswer(cFSM), prob=0.150\n', '9: src=DirectAnswer(cFSM), dst=DirectAnswer(5XF3), prob=0.00\n', '10: src=DirectAnswer(cFSM), dst=DirectAnswer(3CoH), prob=0.000\n', '11: src=DirectAnswer(cFSM), dst=DirectAnswer(4Dhq), prob=0.000\n', '12: src=DirectAnswer(5XF3), dst=FinalDecision(6S5Q), prob=0.000\n', '13: src=DirectAnswer(3CoH), dst=FinalDecision(6S5Q), prob=0.000\n', '14: src=DirectAnswer(4Dhq), dst=FinalDecision(6S5Q), prob=0.000\n', '15: src=DirectAnswer(cFSM), dst=FinalDecision(6S5Q), prob=0.100\n']

Now think step-by-step with the rules above and return the Graph and Edge-probabilities two blocks only.
Disallow the following symbol-sequence pattern: a single space, then several arbitrary tokens, followed by a placeholder or ellipsis.
"""
        return prompt
    
    @staticmethod
    def get_llm_forward_maao(prev_graph,acc,edge_probs,role_probs):

        prompt = f"""
You are a professional **Multi-Agent-System (MAS) optimizer**.  
Your task is an iterative self-RL refinement of a MAS that solves the **MMLU** dataset.

────────────────────────────────────
TASK CONTEXT
────────────────────────────────────
• A MAS is represented as a **directed acyclic graph (DAG)**.  
  - Each **node** = one language-model agent.  
  - Each **directed edge** = “the source agent's output is appended to the destination agent's context”.  
• You will see the **last-round graph**, its **batch accuracy**, and the **full table of edge-selection probabilities,role-selection probabilities**.  
• Your job: updated all probability table based on the accuracy of the previous graph ** (same order & format), applying * RL-style* probability nudges.

────────────────────────────────────
HISTORICAL SNAPSHOT
────────────────────────────────────
Last-round accuracy ( MedQA-dev batch ) : **{acc:.3%}**  
Last-round graph:  
{prev_graph}
Last-round edge-probabilities:
{edge_probs}
Last-round role-probabilities:
{role_probs}

────────────────────────────────────
OPTIMIZATION RULES
────────────────────────────────────
R-1  Return values must keep the identical schema / key order as the inputs — only the values may change.
R-2  If a node appears with model = FinalDecision (this is the single output node of the MAS), do not modify its role's probabilities.
Your optimization may only update the set/probabilities of its incoming edges — that is, adjust which predecessors feed it and with what likelihood—but the node itself must stay unchanged.

────────────────────────────────────
WHAT TO RETURN
────────────────────────────────────
Return ONLY the following **two blocks**, in the order shown below — nothing else:
	1. Edge_probs - the updated probability table, same schema and order as last-round edge-probabilities.
    2. Role-probabilities — updated role assignment probabilities. Must preserve:
   • Same node list as input  
   • Same order  
   • Only values may change
    
Example output format (do NOT add comments):
Edge-probabilities:
['0: src=DirectAnswer(6bfQ), dst=DirectAnswer(jCyH), prob=0.475\n', '1: src=DirectAnswer(jCyH), dst=DirectAnswer(6bfQ), prob=0.475\n', '2: src=DirectAnswer(6bfQ), dst=FinalDecision(oznx), prob=0.475\n', '3: src=DirectAnswer(jCyH), dst=FinalDecision(oznx), prob=0.525\n']
Role-probabilities:
['0: node=FinalDecision(oznx), IO=0.500, REV=0.500\n', '1: node=DirectAnswer(6bfQ), IO=0.550, REV=0.450\n', '2: node=DirectAnswer(jCyH), IO=0.550, REV=0.450\n']

Now think step-by-step with the rules above and return the two probabilities blocks only.
Disallow the following symbol-sequence pattern: a single space, then several arbitrary tokens, followed by a placeholder or ellipsis.
"""
        return prompt
    
    @staticmethod
    def get_llm_forward_latency(prev_graph,acc,edge_probs,model_selection,latency):

        prompt = f"""
You are a professional **Multi-Agent-System (MAS) optimizer**.  
Your task is an iterative self-RL refinement of a MAS that solves the **MMLU** dataset.

────────────────────────────────────
TASK CONTEXT
────────────────────────────────────
• A MAS is represented as a **directed acyclic graph (DAG)**.  
  - Each **node** = one language-model agent.  
  - Each **directed edge** = “the source agent's output is appended to the destination agent's context”.  
• For the current budget we have a fixed **model-selection requirement**:  
  {model_selection}
• You will see the **last-round graph**, its **batch accuracy**, and the **full table of edge-selection probabilities**.  
• Your job: **propose the next-round graph** (same format) **and the updated probability table** (same order & format), applying * RL-style* probability nudges.
• The graph you receive in this iteration has been expanded outward from the FinalDecision node, gradually increasing in both depth and breadth. The edge-probabilities starts with all edge probabilities set to zero, and through multiple sampling rounds, probabilities are raised only for edges that prove useful and efficiency.
• Your goal is to optimize a MAS DAG to minimize inference latency while ensuring it remains highly usable.

────────────────────────────────────
HISTORICAL SNAPSHOT
────────────────────────────────────
Last-round accuracy ( MedQA-dev batch ) : **{acc:.3%}**  
Last-round graph:  
{prev_graph}
Last-round edge-probabilities:
{edge_probs}
Last-round inference latency:
{latency}

────────────────────────────────────
OPTIMIZATION RULES
────────────────────────────────────
R-1  Model counts must exactly match model_selection after you assign models to all nodes.
R-2  A node's role is either "IO" (generates new answer) or "REV" (reviews & picks best).
R-3  Return values must keep the identical schema / key order as the inputs — only the values may change.
R-4  Increase an edge probability **only if it was sampled in the last-round graph AND proved useful**.  
Always start expansion from FinalDecision's incoming edges, then its parents' incoming edges, and so on.
↑ increase edges used by high-accuracy graphs, ↓ decrease edges from poor graphs.
R-5  Keep the graph acyclic; avoid too much in-degree to prevent context explosion; avoid very deep chains to prevent “answer corruption”.
R-6 If a node appears with model = FinalDecision (this is the single output node of the MAS), do not modify its model or role.
Your optimization may only update the set/probabilities of its incoming edges — that is, adjust which predecessors feed it and with what likelihood—but the node itself must stay unchanged.

────────────────────────────────────
DATA and Insight
────────────────────────────────────
• Model accuracy on Math (single-agent):
1 B → 31   3 B → 40   8 B → 48   70 B → 68

Latency Optimization Insights:
• Graphs with fewer nodes generally achieve lower inference latency. You may remove weaker models if doing so does not significantly harm performance.
• Proper control of context length is a key factor for inference latency. Avoid giving a node overly long input contexts — each node's in-degree should not be too large.
• When performance is not heavily impacted, aim to reduce the total number of edges. Sparse graphs have much lower inference latency compared to dense ones.

Performance optimize insight:
• Larger models tolerate longer context and are harder to corrupt.
• Larger models outperform smaller models when assigned the nodes with more predecessors.
• For nodes with multiple incoming edges, assigning diverse models to their predecessors often yields better performance than using a single repeated model.
• The optimal depth is conditioned by current width, and vice-versa: wider graphs shift the depth sweet-spot downward, while deeper graphs reduce the optimal width.
• You should expand the architecture outward from the FinalDecision node, gradually adding depth and width.
• Different tasks favor different graph topologies depending on the model mix. Certain model configurations benefit more from greater depth, while others perform best with greater width. With the current model selection, optimize toward the topology style that this task prefers.
• For this round, increase probabilities only for nodes that boost MAS accuracy, and lower those that harm it.

────────────────────────────────────
WHAT TO RETURN
────────────────────────────────────
Return ONLY two blocks, nothing else.
	1.	graph - the next-round DAG, same schema as last-round graph.
	2.	edge_probs - the updated probability table, same schema and order as last-round edge-probabilities.
IMPORTANT: The "Graph:" block must list exactly the same nodes as in the last-round graph. Do NOT create any new node lines. Do NOT change any node ID token.

Example output format (do NOT add comments):
Graph:
"Node 3CoH | model=llama3.2-3b-longcontext:latest | role=IO | preds=['4Dhq'] | succs=[]\nNode 4Dhq | model=llama3.2-1b-longcontext:latest | role=IO | preds=[] | succs=['3CoH', 'cFSM']\nNode 5XF3 | model=llama3.2-1b-longcontext:latest | role=IO | preds=['cFSM'] | succs=[]\nNode 6S5Q | model=FinalDecision | role=IO | preds=['cFSM'] | succs=[]\nNode cFSM | model=llama3.2-3b-longcontext:latest | role=REV | preds=['4Dhq'] | succs=['5XF3', '6S5Q']"
Edge-probabilities:
['0: src=DirectAnswer(5XF3), dst=DirectAnswer(3CoH), prob=0.000\n', '1: src=DirectAnswer(5XF3), dst=DirectAnswer(4Dhq), prob=0.000\n', '2: src=DirectAnswer(5XF3), dst=DirectAnswer(cFSM), prob=0.000\n', '3: src=DirectAnswer(3CoH), dst=DirectAnswer(5XF3), prob=0.000\n', '4: src=DirectAnswer(3CoH), dst=DirectAnswer(4Dhq), prob=0.000\n', '5: src=DirectAnswer(3CoH), dst=DirectAnswer(cFSM), prob=0.000\n', '6: src=DirectAnswer(4Dhq), dst=DirectAnswer(5XF3), prob=0.000\n', '7: src=DirectAnswer(4Dhq), dst=DirectAnswer(3CoH), prob=0.100\n', '8: src=DirectAnswer(4Dhq), dst=DirectAnswer(cFSM), prob=0.150\n', '9: src=DirectAnswer(cFSM), dst=DirectAnswer(5XF3), prob=0.00\n', '10: src=DirectAnswer(cFSM), dst=DirectAnswer(3CoH), prob=0.000\n', '11: src=DirectAnswer(cFSM), dst=DirectAnswer(4Dhq), prob=0.000\n', '12: src=DirectAnswer(5XF3), dst=FinalDecision(6S5Q), prob=0.000\n', '13: src=DirectAnswer(3CoH), dst=FinalDecision(6S5Q), prob=0.000\n', '14: src=DirectAnswer(4Dhq), dst=FinalDecision(6S5Q), prob=0.000\n', '15: src=DirectAnswer(cFSM), dst=FinalDecision(6S5Q), prob=0.100\n']

Now think step-by-step with the rules and insights above and return the Graph and Edge-probabilities two blocks only. Remember, your primary goal is to decrease the inference latency of the graph, while ensuring that the graph's performance remains usable. 
Disallow the following symbol-sequence pattern: a single space, then several arbitrary tokens, followed by a placeholder or ellipsis.
"""
        return prompt
    
    @staticmethod
    def get_llm_forward_ablation_role(prev_graph,acc,edge_probs,model_selection):

        prompt = f"""
You are a professional **Multi-Agent-System (MAS) optimizer**.  
Your task is an iterative self-RL refinement of a MAS that solves the **MMLU** dataset.

────────────────────────────────────
TASK CONTEXT
────────────────────────────────────
• A MAS is represented as a **directed acyclic graph (DAG)**.  
  - Each **node** = one language-model agent.  
  - Each **directed edge** = “the source agent's output is appended to the destination agent's context”.  
• For the current budget we have a fixed **model-selection requirement**:  
  {model_selection}
• You will see the **last-round graph**, its **batch accuracy**, and the **full table of edge-selection probabilities**.  
• Your job: **propose the next-round graph** (same format) **and the updated probability table** (same order & format), applying * RL-style* probability nudges.
• The graph you receive in this iteration has been expanded outward from the FinalDecision node, gradually increasing in both depth and breadth. The edge-probabilities starts with all edge probabilities set to zero, and through multiple sampling rounds, probabilities are raised only for edges that prove useful.

────────────────────────────────────
HISTORICAL SNAPSHOT
────────────────────────────────────
Last-round accuracy ( MedQA-dev batch ) : **{acc:.3%}**  
Last-round graph:  
{prev_graph}
Last-round edge-probabilities:
{edge_probs}

────────────────────────────────────
OPTIMIZATION RULES
────────────────────────────────────
R-1  Model counts must exactly match model_selection after you assign models to all nodes.
R-2  Do not change node's role only if it is not IO, keep all node's role as IO.
R-3  Return values must keep the identical schema / key order as the inputs — only the values may change.
R-4  Increase an edge probability **only if it was sampled in the last-round graph AND proved useful**.  
Always start expansion from FinalDecision's incoming edges, then its parents' incoming edges, and so on.
↑ increase edges used by high-accuracy graphs, ↓ decrease edges from poor graphs.
R-5  Keep the graph acyclic; avoid too much in-degree to prevent context explosion; avoid very deep chains to prevent “answer corruption”.
R-6 If a node appears with model = FinalDecision (this is the single output node of the MAS), do not modify its model or role.
Your optimization may only update the set/probabilities of its incoming edges — that is, adjust which predecessors feed it and with what likelihood—but the node itself must stay unchanged.

────────────────────────────────────
DATA and Insight
────────────────────────────────────
• Model accuracy on MedQA (single-agent):
1 B → 31   3 B → 43   8 B → 69   70 B → 84

• Larger models tolerate longer context and are harder to corrupt.
• Larger models outperform smaller models when assigned the nodes with more predecessors.
• For nodes with multiple incoming edges, assigning diverse models to their predecessors often yields better performance than using a single repeated model.
• The optimal depth is conditioned by current width, and vice-versa: wider graphs shift the depth sweet-spot downward, while deeper graphs reduce the optimal width.
• You should expand the architecture outward from the FinalDecision node, gradually adding depth and breadth.
• Different tasks favor different graph topologies depending on the model mix. Certain model configurations benefit more from greater depth, while others perform best with greater width. With the current model selection, optimize toward the topology style that this task prefers.
• For this round, increase probabilities only for nodes that boost MAS accuracy, and lower those that harm it.

────────────────────────────────────
WHAT TO RETURN
────────────────────────────────────
Return ONLY two blocks, nothing else.
	1.	graph - the next-round DAG, same schema as last-round graph.
	2.	edge_probs - the updated probability table, same schema and order as last-round edge-probabilities.
IMPORTANT: The "Graph:" block must list exactly the same nodes as in the last-round graph. Do NOT create any new node lines. Do NOT change any node ID token.
    
Example output format (do NOT add comments):
Graph:
"Node 3CoH | model=llama3.2-3b-longcontext:latest | role=IO | preds=['4Dhq'] | succs=[]\nNode 4Dhq | model=llama3.2-1b-longcontext:latest | role=IO | preds=[] | succs=['3CoH', 'cFSM']\nNode 5XF3 | model=llama3.2-1b-longcontext:latest | role=IO | preds=['cFSM'] | succs=[]\nNode 6S5Q | model=FinalDecision | role=IO | preds=['cFSM'] | succs=[]\nNode cFSM | model=llama3.2-3b-longcontext:latest | role=IO | preds=['4Dhq'] | succs=['5XF3', '6S5Q']"
Edge-probabilities:
['0: src=DirectAnswer(5XF3), dst=DirectAnswer(3CoH), prob=0.000\n', '1: src=DirectAnswer(5XF3), dst=DirectAnswer(4Dhq), prob=0.000\n', '2: src=DirectAnswer(5XF3), dst=DirectAnswer(cFSM), prob=0.000\n', '3: src=DirectAnswer(3CoH), dst=DirectAnswer(5XF3), prob=0.000\n', '4: src=DirectAnswer(3CoH), dst=DirectAnswer(4Dhq), prob=0.000\n', '5: src=DirectAnswer(3CoH), dst=DirectAnswer(cFSM), prob=0.000\n', '6: src=DirectAnswer(4Dhq), dst=DirectAnswer(5XF3), prob=0.000\n', '7: src=DirectAnswer(4Dhq), dst=DirectAnswer(3CoH), prob=0.100\n', '8: src=DirectAnswer(4Dhq), dst=DirectAnswer(cFSM), prob=0.150\n', '9: src=DirectAnswer(cFSM), dst=DirectAnswer(5XF3), prob=0.00\n', '10: src=DirectAnswer(cFSM), dst=DirectAnswer(3CoH), prob=0.000\n', '11: src=DirectAnswer(cFSM), dst=DirectAnswer(4Dhq), prob=0.000\n', '12: src=DirectAnswer(5XF3), dst=FinalDecision(6S5Q), prob=0.000\n', '13: src=DirectAnswer(3CoH), dst=FinalDecision(6S5Q), prob=0.000\n', '14: src=DirectAnswer(4Dhq), dst=FinalDecision(6S5Q), prob=0.000\n', '15: src=DirectAnswer(cFSM), dst=FinalDecision(6S5Q), prob=0.100\n']

Now think step-by-step with the rules and insights above and return the Graph and Edge-probabilities two blocks only.
Disallow the following symbol-sequence pattern: a single space, then several arbitrary tokens, followed by a placeholder or ellipsis.
"""
        return prompt
    
    @staticmethod
    def get_model_initialize_latency(model_combo):
        prompt = f"""
You are a researcher specializing in multi-agent systems (MAS).  
Your current task is **model initialization**: under a fixed computational **budget** you must choose an initial set of language-model agents (each model = one node) for a MAS that will later be optimized into a DAG. An edge means the previous agent’s output is the next agent’s input.

================  TASK  =================
1. Examine the **candidate model combinations** listed at the end of this message.  
2. Using the insights and data below, pick **two** combination that achieves the highest efficiency under acceptable performance on the Math dataset.  
3. Return **only** two JSON dictionaries with four integer keys:  
   - `"0"` = number of 1 B models  
   - `"1"` = number of 3 B models  
   - `"2"` = number of 8 B models  
   - `"3"` = number of 70 B models  

No extra text, explanations, or formatting—just the dictionary.

===============  INSIGHTS  ===============
(1) Well-designed MASes usually improve as the number of nodes increases, **but**  
    • very long contexts fed to a weak model can hurt accuracy, and  
    • overly deep DAGs may let later agents overwrite correct answers.
    • both depth and width have an optimal point—beyond that, adding more layers or parallel branches starts to decrease overall performance.
    • Too many weak models may decrease the performance instead of increase.
(2) Stronger models (with higher standalone performance) can handle longer contexts and are less likely to corrupt correct answers, but they are also slower and more costly.
(3) Efficiency should be prioritized:
• Systems with more small models generally have higher inference efficiency (lower latency, lower cost).
• When choosing among combinations, prefer those that use small or efficient models even if their performance is slightly lower—as long as the overall performance remains acceptable.
• The goal is to maximize efficiency under acceptable performance, not to maximize raw accuracy.
(4) You may refer to the 'Data' section showing the performance of different model combinations under the same budget on this dataset to help you decide which two model selection are the best candidates among the current model selection options.

===============  DATA  ===================
● **Single-model accuracy on MMLU (higher is better)**  
1 B → 31   3 B → 43   8 B → 69   70 B → 84
● Random-graph pre-experiments (equal budget):
9X1 B → 30   2X3B + 3X1B → 45  1X3B + 6X1B → 39  3X3B → 41  1X8B → 64  


===============  CANDIDATES  =============
Choose only **two** from this list (each already fits the budget):

{model_combo}

=========================================

Respond with the dictionary **only**. Example format (do NOT copy):  
```json
{{"0":0,"1":4,"2":0,"3":0}}
```json
{{"0":0,"1":1,"2":1,"3":0}}
"""
        return prompt